export const join_room = 'join-room'
export const move_made = 'move-made'
export const listen_to_move='listen-to-move'
export const close_game = 'close-game'
export const player_left = 'player-left'
export const room_exits = 'room-exits'